

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Logo from './images/Surf Pulse.png'
import React from "react";
import Profile from "./components/profileMenu";
import Search from "./components/searchBar";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Surf Pulse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={inter.className}>
        <main>
          <nav className=" flex items-center justify-between h-16">
          <img className="mr-6" src={Logo.src} alt="Logo" />
          <Search />
          <div>
            <Link className="mx-3" href={"/"}>Home</Link>
            <Link className="mx-3" href={"/surfspots"}>Surfspots </Link>
            <Link className="mx-3" href={"/articles"}>Articles</Link>
            <Profile />
          </div>
          </nav>
          <div className="border-b-2 border-black"></div>
        </main>
        {children}
        <Toaster position="top-center" />
      </body>           
    </html>
    
  );
}
